//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Filmi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmi()
        {
            this.Filma_Salla = new HashSet<Filma_Salla>();
        }
    
        public int Id_Filmi { get; set; }
        public string Titulli { get; set; }
        public string Pershkrimi { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Kategoria { get; set; }
        public string Statusi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filma_Salla> Filma_Salla { get; set; }
        public virtual Kategori Kategori { get; set; }
        [DisplayName("Upload file")]
        public HttpPostedFileBase imagefile { get; set; }
    }
}
