//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinemaDBEntities : DbContext
    {
        public KinemaDBEntities()
            : base("name=KinemaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filma_Salla> Filma_Salla { get; set; }
        public virtual DbSet<Filmi> Filmis { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Perdorue> Perdorues { get; set; }
        public virtual DbSet<Rezervimi> Rezervimis { get; set; }
        public virtual DbSet<Roli> Rolis { get; set; }
        public virtual DbSet<Salla> Sallas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
