//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id_log { get; set; }
        public Nullable<int> Id_perdoruesi { get; set; }
        public Nullable<System.DateTime> Data_exc { get; set; }
        public string Mesazhi { get; set; }
    
        public virtual Perdorue Perdorue { get; set; }
    }
}
