//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perdorue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perdorue()
        {
            this.Logs = new HashSet<Log>();
            this.Rezervimis = new HashSet<Rezervimi>();
        }
    
        public int ID_Perdorues { get; set; }
        public string Emer { get; set; }
        public string Mbiemer { get; set; }
        public Nullable<int> NR_Kontakti { get; set; }
        public string Email { get; set; }
        public Nullable<int> ID_Roli { get; set; }
        public string Username { get; set; }
        public string Fjalekalimi { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string Statusi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervimi> Rezervimis { get; set; }
        public virtual Roli Roli { get; set; }
        public string ConfirmFjalekalimi { get; internal set; }
    }
}
