//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salla()
        {
            this.Filma_Salla = new HashSet<Filma_Salla>();
        }
    
        public int Id_Salla { get; set; }
        public string Statusi { get; set; }
        public Nullable<int> Nr_Rreshtave { get; set; }
        public Nullable<int> Nr_Kolonave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filma_Salla> Filma_Salla { get; set; }
    }
}
